CREATE TABLE `ingestion_runs` (
	`id` text PRIMARY KEY NOT NULL,
	`event_id` text,
	`mode` text NOT NULL,
	`status` text NOT NULL,
	`started_at` text NOT NULL,
	`finished_at` text,
	`input_json` text NOT NULL,
	`report_json` text,
	`input_tokens` integer,
	`output_tokens` integer,
	`model_cost_usd` real,
	`search_cost_estimate_usd` real,
	`duration_ms` integer,
	`usage_complete` integer,
	CONSTRAINT "ingestion_runs_mode_ck" CHECK(length(trim("ingestion_runs"."mode")) > 0),
	CONSTRAINT "ingestion_runs_status_ck" CHECK("ingestion_runs"."status" IN ('running', 'completed', 'failed')),
	CONSTRAINT "ingestion_runs_input_ck" CHECK(CASE WHEN json_valid("ingestion_runs"."input_json") THEN json_type("ingestion_runs"."input_json") IS 'object' AND json_extract("ingestion_runs"."input_json", '$.mode') IS "ingestion_runs"."mode" ELSE 0 END),
	CONSTRAINT "ingestion_runs_report_ck" CHECK("ingestion_runs"."report_json" IS NULL OR CASE WHEN json_valid("ingestion_runs"."report_json") THEN json_type("ingestion_runs"."report_json") IS 'object' AND json_extract("ingestion_runs"."report_json", '$.mode') IS "ingestion_runs"."mode" AND json_extract("ingestion_runs"."report_json", '$.runId') IS "ingestion_runs"."id" AND json_extract("ingestion_runs"."report_json", '$.schemaVersion') IS 2 ELSE 0 END),
	CONSTRAINT "ingestion_runs_lifecycle_ck" CHECK(("ingestion_runs"."status" = 'running' AND "ingestion_runs"."finished_at" IS NULL AND "ingestion_runs"."report_json" IS NULL AND "ingestion_runs"."input_tokens" IS NULL AND "ingestion_runs"."output_tokens" IS NULL AND "ingestion_runs"."model_cost_usd" IS NULL AND "ingestion_runs"."search_cost_estimate_usd" IS NULL AND "ingestion_runs"."duration_ms" IS NULL AND "ingestion_runs"."usage_complete" IS NULL) OR ("ingestion_runs"."status" != 'running' AND "ingestion_runs"."finished_at" IS NOT NULL AND "ingestion_runs"."report_json" IS NOT NULL AND "ingestion_runs"."input_tokens" IS NOT NULL AND "ingestion_runs"."output_tokens" IS NOT NULL AND "ingestion_runs"."search_cost_estimate_usd" IS NOT NULL AND "ingestion_runs"."duration_ms" IS NOT NULL AND "ingestion_runs"."usage_complete" IS NOT NULL)),
	CONSTRAINT "ingestion_runs_input_tokens_ck" CHECK("ingestion_runs"."input_tokens" IS NULL OR (typeof("ingestion_runs"."input_tokens") = 'integer' AND "ingestion_runs"."input_tokens" >= 0)),
	CONSTRAINT "ingestion_runs_output_tokens_ck" CHECK("ingestion_runs"."output_tokens" IS NULL OR (typeof("ingestion_runs"."output_tokens") = 'integer' AND "ingestion_runs"."output_tokens" >= 0)),
	CONSTRAINT "ingestion_runs_duration_ms_ck" CHECK("ingestion_runs"."duration_ms" IS NULL OR (typeof("ingestion_runs"."duration_ms") = 'integer' AND "ingestion_runs"."duration_ms" >= 0)),
	CONSTRAINT "ingestion_runs_model_cost_usd_ck" CHECK("ingestion_runs"."model_cost_usd" IS NULL OR "ingestion_runs"."model_cost_usd" >= 0),
	CONSTRAINT "ingestion_runs_search_cost_estimate_usd_ck" CHECK("ingestion_runs"."search_cost_estimate_usd" IS NULL OR "ingestion_runs"."search_cost_estimate_usd" >= 0),
	CONSTRAINT "ingestion_runs_complete_ck" CHECK("ingestion_runs"."usage_complete" IS NULL OR "ingestion_runs"."usage_complete" IN (0, 1))
);
