export type PublicOccurrence = {
  id: string;
  eventId: string;
  key: string;
  eventSlug: string;
  eventName: string;
  name: string | null;
  year: number;
  startsOn: string;
  endsOn: string;
  dateState: "confirmed" | "provisional";
  status: "announced" | "scheduled" | "postponed" | "cancelled";
  ticketCategories: {
    label: string;
    availability?: "unknown" | "available" | "sold_out" | "closed";
  }[];
  venueName: string | null;
  venueAddress: string | null;
  locality: string | null;
  administrativeArea: string | null;
  countryCode: string;
  hasCoordinates: boolean;
  capacityEstimate: number | null;
  priceKind: string | null;
  priceCurrency: string | null;
  priceMinMinor: number | null;
  priceMaxMinor: number | null;
  priceCoverage: string | null;
  priceQualification: string | null;
  terms: { facet: string; name: string }[];
  links: { kind: string; url: string; label: string | null }[];
};
export type PublicEvent = {
  id: string;
  slug: string;
  name: string;
  summary: string | null;
  editions: PublicOccurrence[];
};

export type Genre = { slug: string; name: string; parentSlug: string | null };
export type DiscoverySummary = {
  id: string;
  eventSlug: string;
  eventName: string;
  aliases: string[];
  name: string | null;
  year: number;
  key: string;
  startsOn: string;
  endsOn: string;
  dateState: "confirmed" | "provisional";
  status: "announced" | "scheduled";
  countryCode: string;
  locality: string | null;
  administrativeArea: string | null;
  venueName: string | null;
  latitude: number | null;
  longitude: number | null;
  coordinatePrecision: string;
  timeZone: string | null;
  capacityEstimate: number | null;
  genres: string[];
};
